using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json;
using OmniProduct_CoreDomain.Abstractions;
using OmniProduct_CoreDomain.Models.Suppliers;

namespace OmniProduct_CoreDomain.Models;

[Table("Products")]
public class ActiveProduct : ProductBase, ICatalogItem, IPriceable, IStockable, IDiscountable, IHasImages,
    ISupplierAssignable, IDeprecable, INotificationSource, IEfSyncable
{
    // EF can't map Price directly (no default ctor / not an owned type here), so we flatten it
    // into columns and keep them in sync by hand. Yes, by hand. Don't forget to call SyncEfColumns().

    // EF-friendly shadow of Discounts, because List<string> isn't a mappable column type here.

    // EF-friendly shadow of Images, serialized by hand because nobody configured a value converter.

    // added over time, not in the original constructor

    // notifications generated by this product, picked up by whoever calls it (was on the service, moved here)

    // EF Core needs a parameterless constructor to materialize rows. It leaves Price/Discounts/
    // Images/SuppliersRegions/Warehouse null until someone remembers to call HydrateFromEfColumns().
    public ActiveProduct() : base()
    {
    }

    public ActiveProduct(string id, string name, string slug, Price price, List<string> discounts,
                   Dictionary<string, string> images, Dictionary<string, Supplier> suppliersRegions,
                   double weight, string dimensions, int quantity, int stock ) :
        base(id, name, slug, price, discounts, images, suppliersRegions, weight, dimensions, quantity, stock)
    {
    }

    // Keeps the "real" domain fields and the flattened EF columns in agreement.
    // Nothing calls this automatically - every method below that mutates Price/Discounts/Images
    // has to remember to call it too, and at least one of them below forgets on purpose.

    // Rebuilds the "real" domain fields from the flattened EF columns after EF materializes a row.

    // --- Catalog / images / discounts ---

    // --- Suppliers ---

    // --- Pricing ---

    // --- Stock ---

    // --- Lifecycle ---
    public override string Status { get; set; } = "Active";
}
