namespace OmniProduct_CoreDomain.Models;

public class Product
{

    public string Id { get; set; }


    public string Name { get; set; }


    public string Slug { get; set; }

    public Price Price { get; set; }

    public List<string> Discounts { get; set; }

    public Dictionary<string, string> Images { get; set; }          // key = context (e.g. "thumbnail", "hero"), value = url

    public Dictionary<string, Supplier> SuppliersRegions { get; set; } // key = region, value = supplier


    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // notifications generated by this product, picked up by whoever calls it (was on the service, moved here)
    public List<Notification> Notifications { get; set; } = new();

    public Product()
    {
    }

    public Product(string id, string name, string slug, Price price, List<string> discounts,
                   Dictionary<string, string> images, Dictionary<string, Supplier> suppliersRegions)
    {
        Id = id;
        Name = name;
        Slug = slug;
        Price = price;
        Discounts = discounts;
        Images = images;
        SuppliersRegions = suppliersRegions;
        Status = "active";
        CreatedAt = DateTime.Now;
        UpdatedAt = DateTime.Now;
    }

    public string GetDisplayLabel(int stock)
    {
        if (Status == "deprecated")
            return $"[DISCONTINUED] {Name}";
        if (stock == 0)
            return $"[OUT OF STOCK] {Name}";
        return Name;
    }

    // --- Catalog / images / discounts ---

    public void AddImage(string context, string url)
    {
        Images[context] = url;
        UpdatedAt = DateTime.Now;
    }

    public void AddDiscount(string discountCode)
    {
        Discounts.Add(discountCode);
        UpdatedAt = DateTime.Now;
    }

    // --- Suppliers ---

    public void AddSupplierToRegion(string region, List<Supplier> suppliers)
    {
        var supplier = suppliers.FirstOrDefault(s => s.Region == region);
        if (supplier == null)
            throw new Exception($"No supplier found for region {region}");

        SuppliersRegions[region] = supplier;
        UpdatedAt = DateTime.Now;
    }

    // --- Pricing ---

    public decimal GetResellerPrice()
    {
        return Price.GetResellerPrice();
    }

    public void SetMargin(decimal marginPercent)
    {
        Price.Margin = marginPercent;
        UpdatedAt = DateTime.Now;
    }

    // --- Sales ---

    // Storage owns the actual stock decrement (see StoredProduct.Withdraw); this only
    // records the sale's effect on the catalog side: status flip and notifications.
    public void Sell(int quantity, int remainingStock)
    {
        UpdatedAt = DateTime.Now;

        if (remainingStock == 0)
            Status = "out_of_stock";

        // Notify all regional suppliers
        foreach (var (region, supplier) in SuppliersRegions)
        {
            Notifications.Add(new Notification
            {
                Recipient = supplier.Email,
                Subject = $"Product sold: {Name}",
                Body = $"{quantity} unit(s) of {Name} were sold. Remaining stock: {remainingStock}.",
                Channel = "email",
                SentAt = DateTime.Now
            });
        }
    }

    // --- Lifecycle ---

    public void Deprecate()
    {
        Status = "deprecated";
        UpdatedAt = DateTime.Now;

        // Notify all regional suppliers
        foreach (var (region, supplier) in SuppliersRegions)
        {
            Notifications.Add(new Notification
            {
                Recipient = supplier.Email,
                Subject = $"Product deprecated: {Name}",
                Body = $"The product {Name} has been deprecated and removed from the catalog.",
                Channel = "email",
                SentAt = DateTime.Now
            });
        }

        // Notify customers
        Notifications.Add(new Notification
        {
            Recipient = "customers@omniproduct.com",
            Subject = $"Product no longer available: {Name}",
            Body = $"{Name} is no longer available.",
            Channel = "email",
            SentAt = DateTime.Now
        });
    }
}
